# Generated by Django 6.1 on 2026-08-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(default='general', max_length=30),
            preserve_default=False,
        ),
    ]
