# Generated by Django 6.1 on 2026-09-01 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_appointment_reminder_sent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
