# Generated by Django 6.1 on 2026-09-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
